export const PrimaryCategories = [
    { icon: 'user', title: "Personal", type: "expense" },
    { icon: 'food', title: "Foods & Drink", type: "expense" },
    { icon: 'transport', title: "Transport", type: "expense" },
    { icon: 'grocery', title: "Grocery", type: "expense" },
    { icon: 'travel', title: "Travel", type: "expense" },
    { icon: 'entertainment', title: "Entertainment", type: "expense" },
    { icon: 'fuel', title: "Fuel & Maintenance", type: "expense" },
    { icon: 'bill', title: "Bills & Utilities", type: "expense" },
    { icon: 'medical', title: "Medical", type: "expense" },
    { icon: 'shopping', title: "Shopping", type: "expense" },
    { icon: 'education', title: "Education", type: "expense" },
    { icon: 'office', title: "Office", type: "expense" },
    { icon: 'home', title: "Home", type: "expense" },
    { icon: 'rent', title: "Rent Paid", type: "expense" },
    { icon: 'loan', title: "Loan Paid", type: "expense" },
    { icon: 'donation', title: "Donations / Charity", type: "expense" },
    { icon: 'gift', title: "Gifts", type: "expense" },
    { icon: 'family', title: "Family", type: "expense" },
    { icon: 'fitness', title: "Health & Fitness", type: "expense" },
    { icon: 'wedding', title: "Wedding", type: "expense" },
    { icon: 'mobile', title: "Mobile", type: "expense" },
    { icon: 'electronics', title: "Electronics", type: "expense" },
    { icon: 'insurance', title: "Insurance", type: "expense" },
    { icon: 'money', title: "Installment", type: "expense" },
    { icon: 'expenses', title: "Other Expenses", type: "expense" },
    { icon: 'salary', title: "Salary", type: "income" },
    { icon: 'profits', title: "Business Income/Profit", type: "income" },
    { icon: 'investment', title: "Investment", type: "income" },
    { icon: 'commission', title: "Commission", type: "income" },
    { icon: 'retirement', title: "Pension", type: "income" },
    { icon: 'fund', title: "Allowance", type: "income" },
    { icon: 'bonus', title: "Bonus", type: "income" },
    { icon: 'wallet', title: "Pocket Money", type: "income" },
    { icon: 'freelancer', title: "Freelance", type: "income" },
    { icon: 'gift', title: "Gifts Received", type: "income" },
    { icon: 'rent', title: "Rent Received", type: "income" },
    { icon: 'loan', title: "Loan Received", type: "income" },
    { icon: 'money', title: "Other Income", type: "income" },
    { icon: 'savings', title: "Savings", type: "income" },
]