
const currencies = [
  { code: "AFN", label: "Afghan Afghani", symbol: "؋" },
  { code: "ALL", label: "Albanian Lek", symbol: "L" },
  { code: "DZD", label: "Algerian Dinar", symbol: "د.ج" },
  { code: "AOA", label: "Angolan Kwanza", symbol: "Kz" },
  { code: "ARS", label: "Argentine Peso", symbol: "$" },
  { code: "AMD", label: "Armenian Dram", symbol: "֏" },
  { code: "AWG", label: "Aruban Florin", symbol: "ƒ" },
  { code: "AUD", label: "Australian Dollar", symbol: "A$" },
  { code: "AZN", label: "Azerbaijani Manat", symbol: "₼" },
  { code: "BSD", label: "Bahamian Dollar", symbol: "B$" },
  { code: "BHD", label: "Bahraini Dinar", symbol: "ب.د" },
  { code: "BDT", label: "Bangladeshi Taka", symbol: "৳" },
  { code: "BBD", label: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BYN", label: "Belarusian Ruble", symbol: "Br" },
  { code: "BZD", label: "Belize Dollar", symbol: "BZ$" },
  { code: "XOF", label: "West African CFA franc", symbol: "Fr" },
  { code: "BMD", label: "Bermudian Dollar", symbol: "$" },
  { code: "BTN", label: "Bhutanese Ngultrum", symbol: "Nu." },
  { code: "BOB", label: "Bolivian Boliviano", symbol: "Bs." },
  {
    code: "BAM",
    label: "Bosnia and Herzegovina Convertible Mark",
    symbol: "KM",
  },
  { code: "BWP", label: "Botswana Pula", symbol: "P" },
  { code: "BRL", label: "Brazilian Real", symbol: "R$" },
  { code: "BND", label: "Brunei Dollar", symbol: "B$" },
  { code: "BGN", label: "Bulgarian Lev", symbol: "Лв." },
  { code: "BIF", label: "Burundian Franc", symbol: "FBu" },
  { code: "KHR", label: "Cambodian Riel", symbol: "៛" },
  { code: "CAD", label: "Canadian Dollar", symbol: "C$" },
  { code: "CVE", label: "Cape Verdean Escudo", symbol: "$" },
  { code: "KYD", label: "Cayman Islands Dollar", symbol: "$" },
  { code: "XAF", label: "Central African CFA franc", symbol: "Fr" },
  { code: "CLP", label: "Chilean Peso", symbol: "$" },
  { code: "CNY", label: "Chinese Yuan", symbol: "¥" },
  { code: "COP", label: "Colombian Peso", symbol: "$" },
  { code: "KMF", label: "Comorian Franc", symbol: "CF" },
  { code: "CDF", label: "Congolese Franc", symbol: "FC" },
  { code: "CRC", label: "Costa Rican Colón", symbol: "₡" },
  { code: "HRK", label: "Croatian Kuna", symbol: "kn" },
  { code: "CUP", label: "Cuban Peso", symbol: "$" },
  { code: "CZK", label: "Czech Koruna", symbol: "Kč" },
  { code: "DKK", label: "Danish Krone", symbol: "kr" },
  { code: "DJF", label: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DOP", label: "Dominican Peso", symbol: "RD$" },
  { code: "EGP", label: "Egyptian Pound", symbol: "£" },
  { code: "ERN", label: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "ETB", label: "Ethiopian Birr", symbol: "Br" },
  { code: "EUR", label: "Euro", symbol: "€" },
  { code: "FJD", label: "Fijian Dollar", symbol: "FJ$" },
  { code: "GMD", label: "Gambian Dalasi", symbol: "D" },
  { code: "GEL", label: "Georgian Lari", symbol: "₾" },
  { code: "GHS", label: "Ghanaian Cedi", symbol: "GH₵" },
  { code: "GIP", label: "Gibraltar Pound", symbol: "£" },
  { code: "GTQ", label: "Guatemalan Quetzal", symbol: "Q" },
  { code: "GNF", label: "Guinean Franc", symbol: "FG" },
  { code: "GYD", label: "Guyanese Dollar", symbol: "G$" },
  { code: "HTG", label: "Haitian Gourde", symbol: "G" },
  { code: "HNL", label: "Honduran Lempira", symbol: "L" },
  { code: "HKD", label: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HUF", label: "Hungarian Forint", symbol: "Ft" },
  { code: "ISK", label: "Icelandic Króna", symbol: "kr" },
  { code: "INR", label: "Indian Rupee", symbol: "₹" },
  { code: "IDR", label: "Indonesian Rupiah", symbol: "Rp" },
  { code: "IRR", label: "Iranian Rial", symbol: "﷼" },
  { code: "IQD", label: "Iraqi Dinar", symbol: "د.ع" },
  { code: "ILS", label: "Israeli Shekel", symbol: "₪" },
  { code: "JMD", label: "Jamaican Dollar", symbol: "J$" },
  { code: "JPY", label: "Japanese Yen", symbol: "¥" },
  { code: "JOD", label: "Jordanian Dinar", symbol: "د.ا" },
  { code: "KZT", label: "Kazakhstani Tenge", symbol: "₸" },
  { code: "KES", label: "Kenyan Shilling", symbol: "KSh" },
  { code: "KWD", label: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "KGS", label: "Kyrgyzstani Som", symbol: "сом" },
  { code: "LAK", label: "Lao Kip", symbol: "₭" },
  { code: "LBP", label: "Lebanese Pound", symbol: "ل.ل" },
  { code: "LSL", label: "Lesotho Loti", symbol: "L" },
  { code: "LRD", label: "Liberian Dollar", symbol: "L$" },
  { code: "LYD", label: "Libyan Dinar", symbol: "ل.د" },
  { code: "MOP", label: "Macanese Pataca", symbol: "MOP$" },
  { code: "MKD", label: "Macedonian Denar", symbol: "ден" },
  { code: "MGA", label: "Malagasy Ariary", symbol: "Ar" },
  { code: "MWK", label: "Malawian Kwacha", symbol: "MK" },
  { code: "MYR", label: "Malaysian Ringgit", symbol: "RM" },
  { code: "MVR", label: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "MRU", label: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", label: "Mauritian Rupee", symbol: "₨" },
  { code: "MXN", label: "Mexican Peso", symbol: "$" },
  { code: "MDL", label: "Moldovan Leu", symbol: "L" },
  { code: "MNT", label: "Mongolian Tögrög", symbol: "₮" },
  { code: "MAD", label: "Moroccan Dirham", symbol: "د.م." },
  { code: "MZN", label: "Mozambican Metical", symbol: "MT" },
  { code: "MMK", label: "Burmese Kyat", symbol: "Ks" },
  { code: "NAD", label: "Namibian Dollar", symbol: "N$" },
  { code: "NPR", label: "Nepalese Rupee", symbol: "₨" },
  { code: "ANG", label: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { code: "NZD", label: "New Zealand Dollar", symbol: "NZ$" },
  { code: "NIO", label: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "NGN", label: "Nigerian Naira", symbol: "₦" },
  { code: "NOK", label: "Norwegian Krone", symbol: "kr" },
  { code: "OMR", label: "Omani Rial", symbol: "﷼" },
  { code: "PKR", label: "Pakistani Rupee", symbol: "₨" },
  { code: "PAB", label: "Panamanian Balboa", symbol: "B/." },
  { code: "PGK", label: "Papua New Guinean Kina", symbol: "K" },
  { code: "PYG", label: "Paraguayan Guaraní", symbol: "₲" },
  { code: "PEN", label: "Peruvian Sol", symbol: "S/." },
  { code: "PHP", label: "Philippine Peso", symbol: "₱" },
  { code: "PLN", label: "Polish Zloty", symbol: "zł" },
  { code: "QAR", label: "Qatari Riyal", symbol: "﷼" },
  { code: "RON", label: "Romanian Leu", symbol: "lei" },
  { code: "RUB", label: "Russian Ruble", symbol: "₽" },
  { code: "RWF", label: "Rwandan Franc", symbol: "FRw" },
  { code: "SHP", label: "Saint Helena Pound", symbol: "£" },
  { code: "WST", label: "Samoan Tala", symbol: "WS$" },
  { code: "STD", label: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "SAR", label: "Saudi Riyal", symbol: "﷼" },
  { code: "RSD", label: "Serbian Dinar", symbol: "дин." },
  { code: "SCR", label: "Seychellois Rupee", symbol: "₨" },
  { code: "SLL", label: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SGD", label: "Singapore Dollar", symbol: "S$" },
  { code: "SBD", label: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "SOS", label: "Somali Shilling", symbol: "Sh.So." },
  { code: "ZAR", label: "South African Rand", symbol: "R" },
  { code: "KRW", label: "South Korean Won", symbol: "₩" },
  { code: "SSP", label: "South Sudanese Pound", symbol: "£" },
  { code: "LKR", label: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "SDG", label: "Sudanese Pound", symbol: "ج.س." },
  { code: "SRD", label: "Surinamese Dollar", symbol: "$" },
  { code: "SZL", label: "Swazi Lilangeni", symbol: "L" },
  { code: "SEK", label: "Swedish Krona", symbol: "kr" },
  { code: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { code: "SYP", label: "Syrian Pound", symbol: "£S" },
  { code: "TWD", label: "New Taiwan Dollar", symbol: "NT$" },
  { code: "TJS", label: "Tajikistani Somoni", symbol: "SM" },
  { code: "TZS", label: "Tanzanian Shilling", symbol: "TSh" },
  { code: "THB", label: "Thai Baht", symbol: "฿" },
  { code: "TOP", label: "Tongan Paʻanga", symbol: "T$" },
  { code: "TTD", label: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "TND", label: "Tunisian Dinar", symbol: "د.ت" },
  { code: "TRY", label: "Turkish Lira", symbol: "₺" },
  { code: "TMT", label: "Turkmenistan Manat", symbol: "m" },
  { code: "UGX", label: "Ugandan Shilling", symbol: "USh" },
  { code: "UAH", label: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "AED", label: "United Arab Emirates Dirham", symbol: "د.إ" },
  { code: "GBP", label: "British Pound", symbol: "£" },
  { code: "USD", label: "United States America", symbol: "$" },
  { code: "UYU", label: "Uruguayan Peso", symbol: "$U" },
  { code: "UZS", label: "Uzbekistani Soʻm", symbol: "soʻm" },
  { code: "VUV", label: "Vanuatu Vatu", symbol: "VT" },
  { code: "VEF", label: "Venezuelan Bolívar", symbol: "Bs" },
  { code: "VND", label: "Vietnamese Dong", symbol: "₫" },
  { code: "XPF", label: "CFP Franc", symbol: "₣" },
  { code: "YER", label: "Yemeni Rial", symbol: "﷼" },
  { code: "ZMW", label: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWL", label: "Zimbabwean Dollar", symbol: "Z$" },
];

export default currencies;
