const currencies = [
  { code: "USD", label: "United States Dollar", symbol: "$" },
  { code: "EUR", label: "Euro", symbol: "€" },
  { code: "JPY", label: "Japanese Yen", symbol: "¥" },
  { code: "GBP", label: "British Pound Sterling", symbol: "£" },
  { code: "AUD", label: "Australian Dollar", symbol: "A$" },
  { code: "CAD", label: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", label: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", label: "Chinese Yuan", symbol: "¥" },
  { code: "SEK", label: "Swedish Krona", symbol: "kr" },
  { code: "NZD", label: "New Zealand Dollar", symbol: "NZ$" },
  { code: "MXN", label: "Mexican Peso", symbol: "$" },
  { code: "SGD", label: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", label: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NOK", label: "Norwegian Krone", symbol: "kr" },
  { code: "KRW", label: "South Korean Won", symbol: "₩" },
  { code: "TRY", label: "Turkish Lira", symbol: "₺" },
  { code: "RUB", label: "Russian Ruble", symbol: "₽" },
  { code: "INR", label: "Indian Rupee", symbol: "₹" },
  { code: "BRL", label: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", label: "South African Rand", symbol: "R" },
  { code: "PLN", label: "Polish Zloty", symbol: "zł" },
  { code: "IDR", label: "Indonesian Rupiah", symbol: "Rp" },
  { code: "THB", label: "Thai Baht", symbol: "฿" },
  { code: "MYR", label: "Malaysian Ringgit", symbol: "RM" },
  { code: "PHP", label: "Philippine Peso", symbol: "₱" },
  { code: "VND", label: "Vietnamese Dong", symbol: "₫" },
  { code: "EGP", label: "Egyptian Pound", symbol: "£" },
  { code: "SAR", label: "Saudi Riyal", symbol: "ر.س" },
  { code: "AED", label: "United Arab Emirates Dirham", symbol: "د.إ" },
  { code: "ARS", label: "Argentine Peso", symbol: "$" },
  { code: "CLP", label: "Chilean Peso", symbol: "$" },
  { code: "COP", label: "Colombian Peso", symbol: "$" },
  { code: "PKR", label: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", label: "Bangladeshi Taka", symbol: "৳" },
  { code: "KES", label: "Kenyan Shilling", symbol: "KSh" },
  { code: "NGN", label: "Nigerian Naira", symbol: "₦" },
];

export default currencies;
