import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import DasboardLayout from '@/layout/dashboard.layout'
import useLoadingState from '@/hooks/useLoadingState'
import GlobalProvider from '@/ui/provider/provider'
import Loader from '@/components/loader/loader'
import { dashboardRoutes } from '@/common/settings'
import { usePathname } from 'next/navigation'
import styled from 'styled-components'

const MainWrapper = styled.main`
  html{
    color: ${props => props.theme.color}
  }
`

export default function App({ Component, pageProps }: AppProps) {
  const path = usePathname().split('/')[1];

  const { loading } = useLoadingState();
  return (
    <main>
      <Head>
        <title>Budget Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalProvider>
        <MainWrapper>
          {
            dashboardRoutes.includes(path) ? (
              <DasboardLayout>{!loading ? <Component {...pageProps} /> : <Loader />}</DasboardLayout>
            ) : (<Component {...pageProps} />)
          }
        </MainWrapper>
      </GlobalProvider>
    </main>
  )
}
