import { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

const GeneralLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={popins.className}>{children}</body>
    </html>
  );
};
export default GeneralLayout;
