export const dashboardRoutes: string[] = [
    "dashboard",
    "categories",
    "accounts",
    "transactions",
    'goals',
    'settings',
    'insights'
]
export const Icons: string[] = [
    "user",
    "food",
    "transport",
    "grocery",
    "travel",
    "entertainment",
    "fuel",
    "bill",
    "medical",
    "shopping",
    "education",
    "office",
    "home",
    "rent",
    "loan",
    "donation",
    "gift",
    "family",
    "fitness",
    "wedding",
    "mobile",
    "electronics",
    "insurance",
    "money",
    "expenses",
    "salary",
    "profits",
    "investment",
    "commission",
    "retirement",
    "fund",
    "bonus",
    "wallet",
    "freelancer",
    "gift",
    "rent",
    "loan",
    "money",
    "savings",
]

export const AccountGridItems: string[][] = [
    ['money', 'Cash'],
    ['bank', 'Bank'],
    ['user', 'Person']
]